# We need to extract runtime dependencies
# 
#	<plugin>
#		<artifactId>maven-dependency-plugin</artifactId>
#		<executions>
#			<execution>
#				<id>copy-dependencies</id>
#				<phase>generate-test-resources</phase>
#				<goals>
#					<goal>copy-dependencies</goal>
#				</goals>
#				<inherited>false</inherited>
#				<configuration>
#					<includeScope>runtime</includeScope>
#				</configuration>
#			</execution>
#		</executions>
#	</plugin>

FROM openjdk:14.0.2

COPY target/dependency/* /opt/winter-configuration/jmods

COPY ./target/*.jar /opt/winter-configuration/jmods

WORKDIR /opt/winter-configuration/

CMD [ "java", "-p", "jmods/", "--module", "io.winterframework.mod.configuration/io.winterframework.mod.configuration.app.ConfigurationApp" ]

